# publisher_v2.py
# Module E v2: The Publisher (Narrative Edition)
# 核心目标：生成符合人类阅读习惯的 Markdown，同时保留审计痕迹

import os
import json
from datetime import datetime
from typing import List, Optional

try:
    from rich.console import Console
    from rich.panel import Panel
    console = Console()
except ImportError:
    console = None

from models import VerificationResult

class PublisherAgentV2:
    def __init__(self, output_dir: str = "daily_reports"):
        self.output_dir = output_dir
        if not os.path.exists(output_dir):
            os.makedirs(output_dir)

    def _get_next_version_number(self, date_str: str) -> int:
        """获取指定日期的下一个版本号"""
        import glob
        import re

        # 查找当天所有版本（排除 LATEST）
        pattern = os.path.join(self.output_dir, f"Financial_Briefing_{date_str}_*.md")
        files = glob.glob(pattern)

        # 提取版本号
        version_numbers = []
        for f in files:
            basename = os.path.basename(f)
            if "LATEST" in basename:
                continue
            # 匹配格式: Financial_Briefing_2026-01-29_01.md
            match = re.search(r'_(\d+)\.md$', basename)
            if match:
                version_numbers.append(int(match.group(1)))

        # 返回下一个版本号
        return max(version_numbers, default=0) + 1

    def list_reports(self, date: str = None):
        """列出所有报告版本"""
        import glob

        if date:
            # 列出特定日期的所有版本
            pattern = os.path.join(self.output_dir, f"Financial_Briefing_{date}_*.md")
        else:
            # 列出所有报告
            pattern = os.path.join(self.output_dir, "Financial_Briefing_*.md")

        files = sorted(glob.glob(pattern), reverse=True)  # 最新的在前

        if console:
            from rich.table import Table
            table = Table(title=f"📋 报告版本列表 ({len(files)} 份)")
            table.add_column("文件名", style="cyan")
            table.add_column("大小", justify="right")
            table.add_column("修改时间", style="dim")

            for f in files:
                name = os.path.basename(f)
                size = os.path.getsize(f) / 1024
                mtime = datetime.fromtimestamp(os.path.getmtime(f)).strftime("%Y-%m-%d %H:%M:%S")
                # 标记 LATEST 版本
                if "LATEST" in name:
                    name = f"[bold green]{name}[/]"
                table.add_row(name, f"{size:.1f} KB", mtime)

            console.print(table)
        else:
            for f in files:
                print(os.path.basename(f))

        return files
    
    def generate_daily_report(self, verification_results: List[VerificationResult], include_audit_trail: bool = True) -> Optional[str]:
        if not verification_results: return None

        # 使用日期 + 序号，避免同一天多次运行时覆盖
        now = datetime.now()
        date_str = now.strftime("%Y-%m-%d")

        # 获取下一个版本号
        version_num = self._get_next_version_number(date_str)
        version_str = f"{date_str}_{version_num:02d}"  # 例如: 2026-01-29_01

        file_path = os.path.join(self.output_dir, f"Financial_Briefing_{version_str}.md")

        md = self._generate_markdown(verification_results, date_str)

        with open(file_path, "w", encoding="utf-8") as f:
            f.write(md)

        # 同时保存一个 "LATEST" 版本（固定文件名，方便快速访问）
        latest_path = os.path.join(self.output_dir, f"Financial_Briefing_{date_str}_LATEST.md")
        with open(latest_path, "w", encoding="utf-8") as f:
            f.write(md)

        # 同时保存 JSON 日志（用于追溯，但不展示给普通读者）
        if include_audit_trail:
            self._save_audit_log(verification_results, version_str)
            # 同样保存 latest 版本的 audit log
            latest_log = os.path.join(self.output_dir, f"audit_log_{date_str}_LATEST.json")
            audit_data = [res.model_dump(mode='json') for res in verification_results]
            with open(latest_log, "w", encoding="utf-8") as f:
                json.dump(audit_data, f, ensure_ascii=False, indent=2)

        if console:
            console.print(Panel(
                f"✅ 报告已发布 (版本 {version_num:02d}):\n"
                f"  • 版本存档: {file_path}\n"
                f"  • 最新版本: {latest_path}",
                style="green",
                title="Report Published"
            ))

        return file_path
    
    def _generate_markdown(self, results: List[VerificationResult], date_str: str) -> str:
        # 1. 头部信息
        md = f"""# 📈 AI Financial Briefing ({date_str})

> **Double-Verified**: Content generated by AI and verified against primary sources.
> Citations `` indicate the source of information.

---

"""
        
        for i, result in enumerate(results, 1):
            report = result.report
            
            # 2. 状态徽章 (根据核验结果决定颜色)
            # PASS -> 🟢, PARTIAL -> 🟡, FLAGGED/FAIL -> 🔴
            status_icon = "🟢"
            if result.status == "PARTIAL": status_icon = "🟡 (Audited)"
            elif result.status in ["FAIL", "FLAGGED"]: status_icon = "🔴 (Flagged)"
            
            md += f"## {i}. {report.title} {status_icon}\n\n"
            
            # 3. 正文段落 (直接渲染 Journalist 写好的 Prose)
            # 这里的文本已经包含了
            if report.summary_text:
                md += f"{report.summary_text}\n\n"
            
            if report.background_text:
                md += f"**Background**: \n{report.background_text}\n\n"
                
            if report.analysis_text:
                md += f"**Analysis**: \n{report.analysis_text}\n\n"
                
            if report.outlook_text:
                md += f"**Outlook**: \n{report.outlook_text}\n\n"
            
            # 4. 参考文献 (References) - 你的核心需求
            if report.source_mapping:
                md += "### 📚 References\n"
                # source_mapping 格式: "domain|title|url"
                for idx_str, meta in report.source_mapping.items():
                    try:
                        domain, title, url = meta.split("|")
                        md += f"- **[{idx_str}]** {domain}: [{title}]({url})\n"
                    except ValueError:
                        # 容错处理
                        md += f"- **[{idx_str}]** {meta}\n"
            
            # 5. 审计备注 (Audit Notes) - 仅当有问题时显示
            # 我们过滤掉无关痛痒的 issues，只显示真正的风险
            critical_issues = [iso for iso in result.issues if "Conflict" in iso or "Exaggerated" in iso]
            if critical_issues:
                md += "\n> **⚠️ Audit Alerts**:\n"
                for issue in critical_issues:
                    md += f"> - {issue}\n"
            
            md += "\n---\n"
            
        return md

    def _save_audit_log(self, results: List[VerificationResult], version_str: str):
        """保存详细的 JSON 审计日志（带版本号）"""
        log_path = os.path.join(self.output_dir, f"audit_log_{version_str}.json")
        audit_data = [res.model_dump(mode='json') for res in results]
        with open(log_path, "w", encoding="utf-8") as f:
            json.dump(audit_data, f, ensure_ascii=False, indent=2)
        # 保存日志路径供后续使用
        self._last_log_path = log_path

    def print_final_delivery(self, file_path: str):
        """打印最终交付摘要"""
        if not console:
            return

        from rich.tree import Tree

        tree = Tree("📦 [bold green]最终交付物 (Final Deliverables)[/]")

        # 主报告文件
        tree.add(f"[cyan]研报文件:[/] {file_path}")

        # 审计日志文件（如果存在）
        if hasattr(self, '_last_log_path') and os.path.exists(self._last_log_path):
            tree.add(f"[cyan]审计日志:[/] {self._last_log_path}")

        # 显示文件大小
        if os.path.exists(file_path):
            file_size = os.path.getsize(file_path) / 1024
            tree.add(f"[dim]文件大小: {file_size:.1f} KB[/]")

        console.print(tree)
        console.print(f"\n[bold green]✅ 所有流程已完成！[/]")