# publisher_demo.py
# Module E: The Publisher (Final Delivery)
# V5.1: Markdown Generation + Terminal Output

import os
from datetime import datetime
from typing import List

try:
    from rich.console import Console
    from rich.panel import Panel
    from rich import box
    console = Console()
except ImportError:
    pass

try:
    from auditor_demo import AuditResult
except ImportError:
    exit()

class PublisherAgent:
    def __init__(self, output_dir="daily_reports"):
        self.output_dir = output_dir
        if not os.path.exists(output_dir):
            os.makedirs(output_dir)

    def generate_daily_report(self, audit_results: List[AuditResult]):
        """Generates the Markdown file"""
        if not audit_results:
            console.print("[red]没有可发布的内容。[/]")
            return None

        # Filter valid results
        valid_results = [res for res in audit_results if res.status in ["PASS", "FIXED"]]
        
        if not valid_results:
            console.print("[yellow]所有简报均未通过审计。[/]")
            return None

        date_str = datetime.now().strftime("%Y-%m-%d")
        file_name = f"Financial_Briefing_{date_str}.md"
        file_path = os.path.join(self.output_dir, file_name)

        # Build Markdown content
        md = f"# 📈 AI Financial Briefing ({date_str})\n\n"
        md += "> Generated by AI Agent | Audited by Auto-Auditor\n\n---\n\n"
        
        for i, res in enumerate(valid_results, 1):
            report = res.original_report
            # Use revised summary if fixed
            final_summary = res.revised_summary if res.status == "FIXED" and res.revised_summary else report.summary
            
            status_icon = "🟢" if res.status == "PASS" else "🟡 (Fixed)"
            
            md += f"## {i}. {report.title} {status_icon}\n\n"
            md += f"**Summary**: {final_summary}\n\n"
            
            if report.background:
                md += f"**Background**: \n{report.background}\n\n"
            if report.analysis:
                md += f"**Analysis**: \n{report.analysis}\n\n"
            if report.outlook:
                md += f"**Outlook**: \n{report.outlook}\n\n"

            # ⭐ 原有源：保留一行媒体名概览
            if report.source_refs:
                md += f"> **Source Media**: {', '.join(report.source_refs)}\n\n"

            # ⭐ 新增：详细溯源（网站 + 标题 + URL）
            source_articles = getattr(report, "source_articles", None)
            if source_articles:
                for sa in source_articles:
                    # sa 形如 "domain｜title｜url"
                    try:
                        domain, title, url = sa.split("｜", 3)
                    except ValueError:
                        # 防御性写法：格式不对就直接原样输出
                        md += f"- {sa}\n"
                    else:
                        md += f"- **{domain}**｜{title}  \n  <{url}>\n"
                md += "\n"
            else:
                md += "### 来源溯源 (Sources)\n\n- _无记录_\n\n"
            
            md += "---\n\n"


        with open(file_path, "w", encoding="utf-8") as f:
            f.write(md)
            
        return file_path

    def print_final_delivery(self, file_path: str):
        """Prints the final success message to the terminal"""
        if not file_path: return
        
        console.print("\n")
        console.rule("[bold green]🚀 Module E: 发布完成 (Published)[/]")
        
        console.print(Panel(
            f"✅ **Report Generated Successfully!**\n\n"
            f"📄 Path: [bold underline]{file_path}[/bold underline]\n\n"
            "You can open this Markdown file in VS Code to view the full report.",
            title="System Delivery",
            border_style="green",
            box=box.DOUBLE 
        ))

if __name__ == "__main__":
    pass
