# publisher_v2.py
# Module E v2: auditable Markdown publisher with publication gate.

import json
import os
from datetime import datetime
from typing import List, Optional

try:
    from rich.console import Console
    from rich.panel import Panel

    console = Console()
except ImportError:
    console = None

from models import VerificationResult


class PublisherAgentV2:
    def __init__(self, output_dir: str = "daily_reports"):
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)

    def _get_next_version_number(self, date_str: str) -> int:
        import glob
        import re

        pattern = os.path.join(self.output_dir, f"Financial_Briefing_{date_str}_*.md")
        version_numbers = []
        for path in glob.glob(pattern):
            basename = os.path.basename(path)
            if "LATEST" in basename:
                continue
            match = re.search(r"_(\d+)\.md$", basename)
            if match:
                version_numbers.append(int(match.group(1)))
        return max(version_numbers, default=0) + 1

    def list_reports(self, date: str = None):
        import glob

        pattern = (
            os.path.join(self.output_dir, f"Financial_Briefing_{date}_*.md")
            if date
            else os.path.join(self.output_dir, "Financial_Briefing_*.md")
        )
        files = sorted(glob.glob(pattern), reverse=True)
        if console:
            from rich.table import Table

            table = Table(title=f"Report versions ({len(files)})")
            table.add_column("File", style="cyan")
            table.add_column("Size", justify="right")
            table.add_column("Modified", style="dim")
            for path in files:
                name = os.path.basename(path)
                size = os.path.getsize(path) / 1024
                mtime = datetime.fromtimestamp(os.path.getmtime(path)).strftime("%Y-%m-%d %H:%M:%S")
                table.add_row(name, f"{size:.1f} KB", mtime)
            console.print(table)
        else:
            for path in files:
                print(os.path.basename(path))
        return files

    def generate_daily_report(
        self,
        verification_results: List[VerificationResult],
        include_audit_trail: bool = True,
    ) -> Optional[str]:
        if not verification_results:
            return None

        now = datetime.now()
        date_str = now.strftime("%Y-%m-%d")
        version_num = self._get_next_version_number(date_str)
        version_str = f"{date_str}_{version_num:02d}"
        file_path = os.path.join(self.output_dir, f"Financial_Briefing_{version_str}.md")

        markdown = self._generate_markdown(verification_results, date_str)
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(markdown)

        latest_path = os.path.join(self.output_dir, f"Financial_Briefing_{date_str}_LATEST.md")
        with open(latest_path, "w", encoding="utf-8") as f:
            f.write(markdown)

        if include_audit_trail:
            self._save_audit_log(verification_results, version_str)
            latest_log = os.path.join(self.output_dir, f"audit_log_{date_str}_LATEST.json")
            with open(latest_log, "w", encoding="utf-8") as f:
                json.dump([res.model_dump(mode="json") for res in verification_results], f, ensure_ascii=False, indent=2)

        if console:
            console.print(
                Panel(
                    f"Report published (version {version_num:02d}):\n"
                    f"  - Archive: {file_path}\n"
                    f"  - Latest: {latest_path}",
                    style="green",
                    title="Report Published",
                )
            )
        return file_path

    def _generate_markdown(self, results: List[VerificationResult], date_str: str) -> str:
        allowed = [result for result in results if result.publish_allowed]
        flagged = [result for result in results if not result.publish_allowed]

        md = f"""# AI Financial Briefing ({date_str})

> Double-verified: content generated by AI and verified against source evidence.
> Citations such as `[cite: 1]` point to the reference list under each report.

---

"""
        if allowed:
            md += "## Published Reports\n\n"
            for index, result in enumerate(allowed, 1):
                md += self._render_report(index, result)
        else:
            md += "## Published Reports\n\nNo report passed the publication gate in this run.\n\n---\n"

        if flagged:
            md += "\n## Appendix: Flagged Reports Requiring Review\n\n"
            for index, result in enumerate(flagged, 1):
                md += self._render_report(index, result, appendix=True)

        return md

    def _render_report(self, index: int, result: VerificationResult, appendix: bool = False) -> str:
        report = result.report
        gate = "PASS" if result.publish_allowed else "BLOCKED"
        heading = "###" if appendix else "##"
        md = f"{heading} {index}. {report.title} ({gate})\n\n"

        md += (
            f"> Verified claims: {result.verified_claims} / "
            f"{max(1, result.verified_claims + result.failed_claims + result.not_found_claims)}  \n"
            f"> Evidence hit rate: {result.evidence_hit_rate:.1%}  \n"
            f"> Conflict rate: {result.conflict_rate:.1%}  \n"
            f"> Not found rate: {result.not_found_rate:.1%}  \n"
            f"> Citation diversity: {result.citation_diversity_rate:.1%}  \n"
            f"> Publish gate: {gate} ({result.publish_reason})\n\n"
        )

        if report.summary_text:
            md += f"{report.summary_text}\n\n"
        if report.background_text:
            md += f"**Background**\n\n{report.background_text}\n\n"
        if report.analysis_text:
            md += f"**Analysis**\n\n{report.analysis_text}\n\n"
        if report.outlook_text:
            md += f"**Outlook**\n\n{report.outlook_text}\n\n"

        if report.source_mapping:
            md += "#### References\n\n"
            for idx_str, meta in report.source_mapping.items():
                try:
                    domain, title, url = meta.split("|", 2)
                    md += f"- **[{idx_str}]** {domain}: [{title}]({url})\n"
                except ValueError:
                    md += f"- **[{idx_str}]** {meta}\n"
            md += "\n"

        if result.issues:
            md += "#### Audit Notes\n\n"
            for issue in result.issues:
                md += f"- {issue}\n"
            md += "\n"

        md += "---\n\n"
        return md

    def _save_audit_log(self, results: List[VerificationResult], version_str: str):
        log_path = os.path.join(self.output_dir, f"audit_log_{version_str}.json")
        with open(log_path, "w", encoding="utf-8") as f:
            json.dump([res.model_dump(mode="json") for res in results], f, ensure_ascii=False, indent=2)
        self._last_log_path = log_path

    def print_final_delivery(self, file_path: str):
        if not console:
            return

        from rich.tree import Tree

        tree = Tree("[bold green]Final Deliverables[/]")
        tree.add(f"[cyan]Report file:[/] {file_path}")
        if hasattr(self, "_last_log_path") and os.path.exists(self._last_log_path):
            tree.add(f"[cyan]Audit log:[/] {self._last_log_path}")
        if os.path.exists(file_path):
            tree.add(f"[dim]File size: {os.path.getsize(file_path) / 1024:.1f} KB[/]")
        console.print(tree)
